Oner ince homework 2
upy/bootcamp pull request #40
Opened 2021-12-01 13:38 UTC by OnerInce

Added baskets app
Added orders app
Added category field to products
Added country-city-address to customers model

2021-12-03 10:13 UTC, VeliAliyev approved these changes

2021-12-03 12:53 UTC, AydinAlptug approved these changes

2021-12-03 21:35 UTC, Gormezoglu approved these changes
Great work!

2021-12-04 22:19 UTC, upy requested changes
migration dosyalarini goremedim, ayrica yeni eklenen modellerin adminlerinde arama yaptirabilir miyiz? bazilarinda hata alacagiz gibi duruyor.

2021-12-04 22:19 UTC, upy commented on ecommerce/baskets/models.py
> +                                 on_delete=models.CASCADE, null=True)
blank=True parametresini de eklersek, formlardan blank olarak gelmesine de izin vermis oluruz.

2021-12-04 22:19 UTC, upy commented on ecommerce/baskets/enums.py
> +class Status(models.TextChoices):
BasketStatus dersek, olabilecek diger statuslarla karismasini engellemis oluruz.

2021-12-04 22:19 UTC, upy commented on ecommerce/baskets/models.py
> +        choices=enums.Status.choices, verbose_name=_("Status"), max_length=20)
default BasketStatus.OPEN kayit olustururken bizim icin faydali olur.

2021-12-04 22:19 UTC, upy commented on ecommerce/baskets/models.py
> +        return f"{self.customer} - {self.status}"
customer null olabileceginden buraya self.id de eklersek ayirt etmemizde bize yardimci olur.

2021-12-04 22:19 UTC, upy commented on ecommerce/baskets/models.py
> +    price = models.PositiveIntegerField(verbose_name=_("Price"))
para ile ilgili bir kayit tutacaksak her zaman DecimalField kullanmamiz hesaplamalarda daha kesin olmamizi saglayacaktir.

2021-12-04 22:19 UTC, upy commented on ecommerce/customers/admin.py
> +    list_display = ("name", "line_1", "line_2")
buraya customer da eklersek bizim icin ayirt edici olacaktir.

2021-12-04 22:19 UTC, upy commented on ecommerce/customers/models.py
> +        return f"{self.name}"
bir degisken kullaniyorsak genelde str(self.name) gibi bir kullanim tercih sebebidir.

2021-12-04 22:19 UTC, upy commented on ecommerce/customers/models.py
> +        "Name",
burada sanirim "Name" yerine _("Name") kullanimini atlamisiz? (diger fieldlar icin de sorum gecerlidir)

2021-12-04 22:19 UTC, upy commented on ecommerce/orders/admin.py
> +@admin.register(InvoiceAddress)
odev verirken burada typo olmus, isimlendirme olarak InvoiceAddress yerine ShippingAddress kullanabilir miyiz?

2021-12-04 22:19 UTC, upy commented on ecommerce/orders/admin.py
> +    search_fields = ("customer__full_name", )
customer'in full_name i yok sanirim?

2021-12-04 22:19 UTC, upy commented on ecommerce/orders/models.py
> +                                 on_delete=models.CASCADE)
order kaydinin asla silinememesi gerekir. o yuzden burada tum FK fieldlarda hep PROTECT kullanmaliyiz.

2021-12-04 22:19 UTC, upy commented on ecommerce/orders/models.py
> +        verbose_name = _("bank account")
order bank account olacakti sanirim?

2021-12-04 22:19 UTC, upy commented on ecommerce/products/models.py
> +    categories = models.ManyToManyField(Category)
buraya da bi verbose_name vermemiz faydali olabilir.

2021-12-04 22:19 UTC, upy commented on ecommerce/customers/models.py
> +
customer'i da FK olarak baglayabilir miyiz? odevde bahsetmeyi unutmusum.

2021-12-04 22:19 UTC, upy commented on ecommerce/customers/admin.py
> +
search fields ekleyebilir miyiz?

2021-12-04 22:19 UTC, upy commented on ecommerce/customers/admin.py
> +    list_display = ("name", )
search fields ekleyebilir miyiz?

2021-12-04 22:19 UTC, upy commented on ecommerce/orders/models.py
> +class InvoiceAddress(BaseAbstractModel):
odevde typo olmus bunu ShippingAddress olarak degistirebilir miyiz?

2021-12-04 22:19 UTC, upy commented on ecommerce/orders/models.py
> +    shipping_address = models.CharField(max_length=255, verbose_name=_("Shipping Address"))
degistirdigimiz ShippingAddress'i buraya FK olarak tanimlayabilir miyiz?

2022-11-20 23:09 UTC, closed without merging