Veli Aliev homework 2
upy/bootcamp pull request #41
Opened 2021-12-02 14:27 UTC by VeliAliyev

2021-12-03 09:59 UTC, OnerInce approved these changes

2021-12-03 12:46 UTC, AydinAlptug approved these changes

2021-12-03 21:39 UTC, Gormezoglu approved these changes

2021-12-03 22:18 UTC, eibrahimarisoy approved these changes

2021-12-04 22:20 UTC, upy requested changes
yeni eklenen modellerin adminlerinde arama yaptirabilir miyiz? bazilarinda hata alacagiz gibi duruyor.

2021-12-04 22:20 UTC, upy commented on ecommerce/baskets/enums.py
> +class Status(models.TextChoices):
BasketStatus dersek, olabilecek diger statuslarla karismasini engellemis oluruz.

2021-12-04 22:20 UTC, upy commented on ecommerce/baskets/models.py
> +    customer = models.ForeignKey(Customer, verbose_name=_("Customer"), null=True, on_delete=models.SET_NULL)
blank=True parametresini de eklersek, formlardan blank olarak gelmesine de izin vermis oluruz.

2021-12-04 22:20 UTC, upy commented on ecommerce/baskets/models.py
> +        return f"{self.customer} - {self.status}"
customer null olabileceginden buraya self.id de eklersek ayirt etmemizde bize yardimci olur.

2021-12-04 22:20 UTC, upy commented on ecommerce/customers/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-11-28 09:32
main'e merge edilmis migration dosyalarini degistirmememiz (ozel durumlar haric) gerekir, bu dosya onceden db'e uygulandigi icin tekrardan uygulanmayacak ve address tablosu vs olusmayacaktir.

2021-12-08 10:03 UTC, closed without merging