AydinAlptug - Homework - 2
upy/bootcamp pull request #43
Opened 2021-12-03 12:34 UTC by AydinAlptug

**hw-2 part-1:** category model added to products app and categories field added to product model
**hw-2 part-2:** address, country, city models added to the customers app
**hw-2 part-3:** basket, basketItem models added to the basket app and validation bug fix on customers app
**hw-2 part-4:** bank, bankaccount models added to the payments app
**hw-2 part-5:** order app models added

2021-12-03 21:40 UTC, VeliAliyev commented on ecommerce/orders/models.py
> +    total_price = models.PositiveIntegerField(verbose_name=_("Total Price"))
I think it's better to use models.DecimalField for price in OrderItem model and total_price in Order model

2021-12-03 21:41 UTC, VeliAliyev commented
In orders app, I think it's better to use models.DecimalField for price in OrderItem model and total_price in Order model

2021-12-03 21:41 UTC, VeliAliyev approved these changes

2021-12-03 21:43 UTC, eibrahimarisoy approved these changes

2021-12-03 21:51 UTC, Gormezoglu approved these changes

2021-12-04 11:13 UTC, oguzhancvdr approved these changes
- i can just say that maybe you can create an abstract address model in our core model and you can use it whereever you need.

2021-12-04 12:19 UTC, AydinAlptug commented
> * i can just say that maybe you can create an abstract address model in our core model and you can use it whereever you need.

Thanks for the review, and advice. Definitely, much loosely coupled way to do :+1:

2021-12-04 22:29 UTC, upy requested changes

2021-12-04 22:29 UTC, upy commented on ecommerce/baskets/models.py
> +    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE)
blank=True parametresini de eklersek, formlardan blank olarak gelmesine de izin vermis oluruz.

2021-12-04 22:29 UTC, upy commented on ecommerce/baskets/models.py
> +        return f"{self.customer} - {self.status}"
customer null olabileceginden buraya self.id de eklersek ayirt etmemizde bize yardimci olur.

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/models.py
> +    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
verbose_name'leri unutmazsak guzel olur.

2021-12-04 22:29 UTC, upy commented on ecommerce/orders/models.py
> +        return super().__str__()
islem yapmayacaksak bunu eklememize gerek yok diyebilirim.

2021-12-04 22:29 UTC, upy commented on ecommerce/orders/models.py
> +class BillingAddress(Address):  # Inherited from customers app model Address
bu durum DB'de nasil bir yapi olusturuyor, DB'e bakabilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/payments/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-11-28 11:15
bu dosyada bir karisiklik olmus, products altindaki dosya silinmis sanki?

2021-12-04 22:29 UTC, upy commented on ecommerce/products/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-11-28 10:29
main branch'e merge edilmis migration dosyalarini silmek veya degistirmek 'normal sartlar altinda' hic yapilmamali.

2021-12-04 22:29 UTC, upy commented on ecommerce/products/models.py
> +    categories = models.ManyToManyField(Category)
verbose_name ekleyebilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/baskets/admin.py
> +
search_fields eklense guzel olur mu?

2021-12-04 22:29 UTC, upy commented on ecommerce/baskets/admin.py
> +    list_display = ("product", "quantity", "price",)
search_fields eklense guzel olur mu?

2021-12-04 22:29 UTC, upy commented on ecommerce/baskets/models.py
> +    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE)
basketi olan customer silinmesine izin vermemeliyiz.

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/admin.py
> +    list_display = ("name",)
search fields ekleyebilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/admin.py
> +    list_display = ("name", "country",)
search fields ekleyebilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/admin.py
> +    list_display = ("name", "line1", "line2", "district", "city", "postal_code",)
search fields ekleyebilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/models.py
> +    # phone = RegexValidator(r'^(5)([0-9]{2})\s?([0-9]{3})\s?([0-9]{2})\s?([0-9]{2})$', message="Phone number must be entered in the format: '555 987 65 43' or '5559876543'.") # TR specific
kod icerisinde yorum haline getirilmis kod parcasi birakmak tercih edilen bir yontem degil.

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/models.py
> +    phone = models.CharField(max_length=255, verbose_name=_("Phone"), validators=[phone_validator])
help_text olarak formati yazmamiz faydali olabilir mi?

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/models.py
> +                           message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
mesahi multi language uyumlu yapabilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/orders/admin.py
> +
search fields ekleyebilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/payments/admin.py
> +    list_display = ("name",)
search fields ekleyebilir miyiz?

2021-12-04 22:29 UTC, upy commented on ecommerce/baskets/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-11-28 11:15
products altindaki migrations dosyasini silmisiz sanirim?

2021-12-04 22:29 UTC, upy commented on ecommerce/customers/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-11-28 09:32
main'e merge edilmis migration dosyalarini degistirmememiz (ozel durumlar haric) gerekir, bu dosya onceden db'e uygulandigi icin tekrardan uygulanmayacak ve address tablosu vs olusmayacaktir.

2021-12-04 22:29 UTC, upy commented on ecommerce/orders/models.py
> +        return super().__str__()
eger bir degisiklik yapmiyorsak genelde override etmiyoruz.

2021-12-04 22:29 UTC, upy commented on ecommerce/payments/models.py
> +                                 message="Invalid format.")
hata mesaji multilanguage olursa guzel olur.

2021-12-04 22:29 UTC, upy commented on ecommerce/orders/models.py
> +class OrderBankAccount(BankAccount): # Inherited from payments app model BankAccount
burada veritabaninda nasil bir durum olusuyor kontrol edebilir miyiz?

2021-12-07 21:31 UTC, closed without merging