eylultuncel-homework 2
upy/bootcamp pull request #44
Opened 2021-12-03 14:19 UTC by eylultuncel

new models added to the system

2021-12-03 21:36 UTC, eibrahimarisoy approved these changes

2021-12-03 21:53 UTC, Gormezoglu approved these changes

2021-12-04 10:17 UTC, Tahakbas approved these changes

2021-12-04 13:39 UTC, ttoygar commented on ecommerce/customers/admin.py
> +class ProductAdmin(admin.ModelAdmin):
This class name should be CityAdmin by convention

2021-12-04 14:18 UTC, ttoygar approved these changes
It may be better to use slightly more docstrings.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/customers/admin.py
> +class ProductAdmin(admin.ModelAdmin):
This should be CountryAdmin.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/customers/admin.py
> +class ProductAdmin(admin.ModelAdmin):
This class name should be CityAdmin by convention

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/customers/models.py
> +    phone = models.CharField(max_length=255, verbose_name=_("Phone"))
It might be good to add some regex validators to this.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/customers/models.py
> +    post_code = models.IntegerField(verbose_name=_("Post Code"))
It might be good to add some regex validators to this too.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/orders/models.py
> +    phone = models.CharField(max_length=255, verbose_name=_("Phone"))
It might be good to add some regex validators to this.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/orders/models.py
> +    post_code = models.IntegerField(verbose_name=_("Post Code"))
It might be good to add some regex validators to this.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/payments/admin.py
> +class ProductAdmin(admin.ModelAdmin):
Should be BankAdmin.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/payments/admin.py
> +class ProductAdmin(admin.ModelAdmin):
Should be BankAccountAdmin.

2021-12-04 14:18 UTC, ttoygar commented on ecommerce/products/admin.py
> +class ProductAdmin(admin.ModelAdmin):
Should be CategoryAdmin

2021-12-04 22:37 UTC, upy requested changes
yeni eklenen modellerin adminlerinde arama yaptirabilir miyiz? bazilarinda hata alacagiz gibi duruyor.

2021-12-04 22:37 UTC, upy commented on ecommerce/baskets/enums.py
> +class Status(models.TextChoices):
BasketStatus dersek, olabilecek diger statuslarla karismasini engellemis oluruz.

2021-12-04 22:37 UTC, upy commented on ecommerce/customers/admin.py
> +    inlines = [AddressInline]
citynin adreslerini gormek adminde guzel bir fikir olmayabilir.

2021-12-04 22:37 UTC, upy commented on ecommerce/customers/models.py
> +
customer'i da FK olarak baglayabilir miyiz? odevde bahsetmeyi unutmusum.

2021-12-04 22:37 UTC, upy commented on ecommerce/orders/models.py
> +    bank = models.ForeignKey(Bank, verbose_name="Bank", on_delete=models.PROTECT)
bank modelindeki bank name degistirilirse order zamanindaki secilen bank name tutarsiz olurmis olur.

2021-12-04 22:37 UTC, upy commented on ecommerce/products/models.py
> +    categories = models.ManyToManyField(Category)
verbose_name eklesek guzel olur.

2021-12-08 13:55 UTC, closed without merging