smlblr homework 2
upy/bootcamp pull request #52
Opened 2021-12-04 02:08 UTC by smlblr

Added apps and models:

- Product category
- Core (Regex Validators)
- Customers address
- Baskets
- Orders
- Payments

Extras:
- Phone number and IBAN number validator was made with regex.
- Readme file updated.

2021-12-04 06:03 UTC, eibrahimarisoy approved these changes

2021-12-04 21:07 UTC, ozon-uk approved these changes

2021-12-04 23:20 UTC, upy requested changes
yeni eklenen modellerin adminlerinde arama yaptirabilir miyiz? bazilarinda hata alacagiz gibi duruyor.

2021-12-04 23:20 UTC, upy commented on ecommerce/locale/tr/LC_MESSAGES/django.po
> +#, fuzzy
duzenledikten sonra bunu silmemizde fayda var.

2021-12-04 23:58 UTC, smlblr commented on ecommerce/locale/tr/LC_MESSAGES/django.po
> +#, fuzzy
.po dosyasını koymamız gerektiğini düşünüyordum. Çünkü burada bulunan öbeklerin ingilizce olanlar, zaten kod aralarında yer alıyor ve Türkçesini de burada belirtiyoruz. Neden silmeliyiz?

2021-12-05 06:40 UTC, merged

2021-12-09 06:59 UTC, upy commented on ecommerce/locale/tr/LC_MESSAGES/django.po
> +#, fuzzy
po file'i elbette repomuza ekleyecegiz. silmemiz gereken derken fuzzy satirindan bahsetmistim.
ℹ️ 
#, fuzzy satiri esasinda alt satirdaki ceviride kendisinin bize bir oneri yaptigini belirtiyor, biz buna bakiyoruz uygunsa veya degilse duzeltmesini yapiyoruz ve ```#, fuzzy``` yazisini siliyoruz.