Utkuaysev homework 2
upy/bootcamp pull request #58
Opened 2021-12-04 09:33 UTC by utkuaysev

2021-12-04 10:15 UTC, Tahakbas approved these changes

2021-12-04 13:10 UTC, Shathra approved these changes

2021-12-05 00:01 UTC, upy requested changes

2021-12-05 00:01 UTC, upy commented on ecommerce/basket/admin.py
> +from orders.models import Order
order admin siniflarini buraya neden ekledigimizi anlayamadim.

2021-12-05 00:01 UTC, upy commented on ecommerce/customers/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-11-28 09:32
main'e merge edilmis migration dosyalarini degistirmememiz (ozel durumlar haric) gerekir, bu dosya onceden db'e uygulandigi icin tekrardan uygulanmayacak ve country tablosu vs olusmayacaktir.

2021-12-05 00:01 UTC, upy commented on ecommerce/ecommerce/utils.py
> +class Regex:
core klasoru icine koymak daha iyi bir fikir olabilir.

2021-12-05 00:01 UTC, upy commented on ecommerce/payments/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-11-28 11:15
products icerisindeki migration file silinmis sanki?

2021-12-11 22:46 UTC, closed without merging