Oner ince homework 3
upy/bootcamp pull request #69
Opened 2021-12-10 19:27 UTC by OnerInce

2021-12-10 21:22 UTC, sahinof approved these changes

2021-12-11 09:04 UTC, VeliAliyev commented on ecommerce/baskets/serializers.py
> +
In detailed serializers, maybe it's better to inherit from  the non-detailed serializer. For example, here in BasketDetailedSerializer, if inherit from BasketSerializer you don't need to repeat class Meta.

2021-12-11 09:06 UTC, VeliAliyev commented on ecommerce/baskets/serializers.py
> +
In detailed serializers, maybe it's better to inherit from  the non-detailed serializer. For example, here in BasketDetailedSerializer, if inherit from BasketSerializer you don't need to repeat class Meta.

2021-12-11 23:18 UTC, upy requested changes

2021-12-11 23:18 UTC, upy commented on ecommerce/baskets/filters.py
> +    customer = CustomerFilter
boyle bir tanimi nereden ogrendik? daha once boyle bir tanim gormemistim.

2021-12-11 23:18 UTC, upy commented on ecommerce/baskets/serializers.py
> +    def create(self, validated_data):
detailed serializer'lari genelde create/update icin (ozel durumlar haric) kullanmamaya calisiyoruz, ayrica basket olusturulurken customer olusturmak cok kullanisli degil sanki?

2021-12-11 23:18 UTC, upy commented on ecommerce/orders/serializers.py
> +    city = CitySerializer(many=False)
default many degeri false olmasi lazim, bu nedenle tanim yapmamiza gerek yok sanki?

2021-12-11 23:18 UTC, upy commented on ecommerce/orders/serializers.py
> +    def create(self, validated_data):
endpointi kullanarak hic buradaki methodu call edebildiniz mi?

2022-11-20 23:09 UTC, closed without merging