EmincanYazgi-homework3
upy/bootcamp pull request #72
Opened 2021-12-10 22:05 UTC by ecanyazgi

2021-12-10 23:00 UTC, eibrahimarisoy commented on ecommerce/baskets/serializers.py
> +        manager = BasketQuerySet.as_manager()
manager alanı modelde tanımlanıyor.

2021-12-11 00:09 UTC, ecanyazgi commented on ecommerce/baskets/serializers.py
> +        manager = BasketQuerySet.as_manager()
Hocam çalışmayınca  zaten models kısmına eklemiştim, silmeyi unutmuşum.

2021-12-11 23:09 UTC, upy requested changes

2021-12-11 23:09 UTC, upy commented on ecommerce/baskets/migrations/0001_initial.py
> -# Generated by Django 3.2.9 on 2021-12-03 17:37
migration dosyalarinda ozel durumlar haric degisiklik yapmamamiz gerekiyor.

2021-12-11 23:09 UTC, upy commented on ecommerce/customers/managers.py
> +        return self.select_related("city", "customer" ).order_by('id')
ordering icin gerekiyorsa viewset icerisinde tanimlama yapmamiz faydali olacaktir.
https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter

2021-12-18 17:05 UTC, closed without merging