BeyzaaKoroglu - Homework 3
upy/bootcamp pull request #73
Opened 2021-12-11 05:16 UTC by BeyzaaKoroglu

2021-12-11 05:32 UTC, eibrahimarisoy commented on ecommerce/ecommerce/urls.py
> +router.register("shipping_addresses", ShippingAddressViewSet)
url tanımlamalarında "_" değilde "-" kullanman daha iyi.
https://restfulapi.net/resource-naming/
burdan bakabilirsin.

2021-12-11 14:32 UTC, oguzhancvdr reviewed
- When you create a serializer you can define read_only_fields = [] under the Meta class
- It is used for fields which is already handled by our database for instance; id, created_at, updated_at
- thus, let leave them database to deal with by adding them into  read_only_fields

2021-12-11 23:22 UTC, upy requested changes

2021-12-11 23:22 UTC, upy commented on ecommerce/ecommerce/settings.py
> +    'PAGE_SIZE': 100
bunu env icerisinden alsak daha iyi olur mu?

2021-12-12 06:37 UTC, merged

2021-12-12 21:46 UTC, AydinAlptug commented on ecommerce/orders/serializers.py
> +class OrderBankAccountDetailedSerializer(OrderBankAccountSerializer):
OrderBankAccountDetailedSerializer sınıfı iki kez tanımlanmış

2021-12-12 21:49 UTC, upy commented on ecommerce/orders/serializers.py
> +class OrderBankAccountDetailedSerializer(OrderBankAccountSerializer):
> OrderBankAccountDetailedSerializer

fazlaligi silen bir PR acabilirsen fixleyelim.